<a href="https://colab.research.google.com/github/BJB0/DeepLearning-Pytorch/blob/main/Pytorch_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [97]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [98]:
df = pd.read_csv("/content/breast-cancer.csv")

In [99]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [100]:
df.shape

(569, 32)

In [101]:
df.drop(columns=['id'],inplace=True)

In [102]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

**TRAIN_TEST_SPLIT**

In [103]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1],df.iloc[:,0],test_size=0.2)

**SCALING**

In [104]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train.values.reshape(-1, 1))
X_test = scaler.transform(X_test.values.reshape(-1, 1))

In [105]:
X_train

array([[-0.8969086 ],
       [-0.24990607],
       [-0.03805568],
       [-1.31402483],
       [-0.16688362],
       [-0.35583126],
       [ 1.44775987],
       [-0.6907839 ],
       [-0.12107813],
       [ 1.43344566],
       [-0.95989115],
       [-0.51042478],
       [ 0.16234334],
       [-0.49038488],
       [-0.84537742],
       [ 0.37991941],
       [-0.78812056],
       [-0.56195596],
       [ 0.98970498],
       [-1.13452457],
       [-0.69937243],
       [-0.49897341],
       [-0.27567165],
       [ 1.62525614],
       [-0.73945223],
       [-1.4351231 ],
       [ 1.75980977],
       [-0.82247468],
       [-0.5046991 ],
       [-1.10017046],
       [-0.6907839 ],
       [-0.64784125],
       [-1.22384528],
       [-0.00942725],
       [-0.04664421],
       [ 1.57945065],
       [-0.42167665],
       [-0.96275399],
       [-0.14398087],
       [-0.32433999],
       [ 1.73976987],
       [-0.91981134],
       [-0.44744224],
       [-0.24704322],
       [-0.93412556],
       [-0

In [106]:
y_train

474    B
466    B
387    B
557    B
171    M
      ..
209    B
304    B
531    B
550    B
480    B
Name: diagnosis, Length: 455, dtype: object

**LABEL ENCODING**

In [107]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [108]:
y_train

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

**NUMPY ARRAYS TO PYTORCH TENSORS**

In [109]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [110]:
X_train_tensor.shape

torch.Size([455, 1])

In [111]:
y_train_tensor.shape

torch.Size([455])

In [112]:
from torch.utils.data import Dataset, DataLoader

In [113]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels =labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [114]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)


In [115]:
train_dataset[10]

(tensor([-0.9599]), tensor(0.))

In [116]:
train_loader = DataLoader(train_dataset, batch_size=2, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

**DEFINING THE MODEL**

In [117]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self,num_feautures):

    super().__init__()
    self.linear = nn.Linear(num_features=1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

**IMPORTANT PARAMETERS**

In [118]:
learning_rate = 0.1
epochs = 25

In [119]:
import torch.nn as nn

# Redefining MySimpleNN class with the fix, as the original definition had an error.
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    # Corrected: Use in_features and out_features
    self.linear = nn.Linear(in_features=num_features, out_features=1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

**TRAINING PIPELINE**

In [120]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.15068823099136353
Epoch: 2, Loss: 0.10393016040325165
Epoch: 3, Loss: 0.0874871090054512
Epoch: 4, Loss: 0.07931951433420181
Epoch: 5, Loss: 0.07468394935131073
Epoch: 6, Loss: 0.07186932116746902
Epoch: 7, Loss: 0.07009252905845642
Epoch: 8, Loss: 0.06894386559724808
Epoch: 9, Loss: 0.06818995624780655
Epoch: 10, Loss: 0.06769033521413803
Epoch: 11, Loss: 0.06735703349113464
Epoch: 12, Loss: 0.06713367253541946
Epoch: 13, Loss: 0.06698357313871384
Epoch: 14, Loss: 0.06688260287046432
Epoch: 15, Loss: 0.06681454926729202
Epoch: 16, Loss: 0.0667685717344284
Epoch: 17, Loss: 0.06673764437437057
Epoch: 18, Loss: 0.06671664118766785
Epoch: 19, Loss: 0.06670249998569489
Epoch: 20, Loss: 0.06669291853904724
Epoch: 21, Loss: 0.06668644398450851
Epoch: 22, Loss: 0.06668204814195633
Epoch: 23, Loss: 0.06667910516262054
Epoch: 24, Loss: 0.06667712330818176
Epoch: 25, Loss: 0.06667576730251312


**EVALUATION**

In [121]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.8246
