<a href="https://colab.research.google.com/github/BJB0/DeepLearning-Pytorch/blob/main/Pytorch_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [53]:
df = pd.read_csv("/content/breast-cancer.csv")

In [54]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [55]:
df.shape

(569, 32)

In [56]:
df.drop(columns=['id'],inplace=True)

In [57]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

**TRAIN_TEST_SPLIT**

In [58]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1],df.iloc[:,0],test_size=0.2)

**SCALING**

In [59]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train.values.reshape(-1, 1))
X_test = scaler.transform(X_test.values.reshape(-1, 1))

In [60]:
X_train

array([[-1.33188486e-01],
       [-9.97930983e-01],
       [-7.28400854e-01],
       [-7.59284515e-01],
       [ 1.41380215e+00],
       [-1.72494963e-01],
       [ 7.11900773e-01],
       [ 4.11486983e-01],
       [-1.77002250e+00],
       [ 7.73819273e-02],
       [-4.42025092e-01],
       [ 2.54261074e-01],
       [-1.05112431e-01],
       [-2.98837211e-01],
       [-5.99251001e-01],
       [ 1.16688404e-01],
       [ 8.38243021e-01],
       [-8.49127891e-01],
       [ 5.21134777e-02],
       [-5.68367340e-01],
       [-1.30817139e+00],
       [-4.53255514e-01],
       [-1.21355509e+00],
       [-6.52595506e-01],
       [-3.97103404e-01],
       [ 1.71702355e+00],
       [ 5.77286887e-02],
       [-3.38143688e-01],
       [ 1.70298552e+00],
       [ 3.69357783e+00],
       [ 1.03477541e+00],
       [-1.52912995e+00],
       [-5.29060863e-01],
       [-1.49880781e+00],
       [ 1.74790721e+00],
       [-8.43512680e-01],
       [-3.46566505e-01],
       [-2.93070821e-02],
       [-7.0

In [61]:
y_train

278    B
113    B
348    B
410    B
83     M
      ..
549    B
127    M
31     M
28     M
223    M
Name: diagnosis, Length: 455, dtype: object

**LABEL ENCODING**

In [62]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [63]:
y_train

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,

**NUMPY ARRAYS TO PYTORCH TENSORS**

In [64]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [65]:
X_train_tensor.shape

torch.Size([455, 1])

In [66]:
y_train_tensor.shape

torch.Size([455])

**DEFINING THE MODEL**

In [67]:
class MySimpleNN():

  def __init__(self,X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_frad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss








**IMPORTANT PARAMETERS**

In [68]:
learning_rate = 0.1
epochs = 25

**TRAINING MODEL**

In [69]:
class MySimpleNN():

  def __init__(self,X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7000716964920245
Epoch: 2, Loss: 0.6981127684948039
Epoch: 3, Loss: 0.6962478690474212
Epoch: 4, Loss: 0.6944727029990466
Epoch: 5, Loss: 0.692783143589206
Epoch: 6, Loss: 0.6911752288625308
Epoch: 7, Loss: 0.6896451578395613
Epoch: 8, Loss: 0.6881892864820447
Epoch: 9, Loss: 0.6868041234891723
Epoch: 10, Loss: 0.6854863259589957
Epoch: 11, Loss: 0.6842326949469656
Epoch: 12, Loss: 0.6830401709511456
Epoch: 13, Loss: 0.6819058293512301
Epoch: 14, Loss: 0.6808268758260958
Epoch: 15, Loss: 0.679800641772226
Epoch: 16, Loss: 0.6788245797430478
Epoch: 17, Loss: 0.6778962589269905
Epoch: 18, Loss: 0.6770133606799484
Epoch: 19, Loss: 0.6761736741258267
Epoch: 20, Loss: 0.675375091836952
Epoch: 21, Loss: 0.6746156056043868
Epoch: 22, Loss: 0.673893302306541
Epoch: 23, Loss: 0.6732063598829936
Epoch: 24, Loss: 0.6725530434190649
Epoch: 25, Loss: 0.6719317013454366


In [70]:
model.weights

tensor([[0.1265]], dtype=torch.float64, requires_grad=True)

In [71]:
model.bias

tensor([-0.2416], dtype=torch.float64, requires_grad=True)

**EVALUATION**

In [72]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6228070259094238
