<a href="https://colab.research.google.com/github/BJB0/DeepLearning-Pytorch/blob/main/Tensors_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors are Multi-dimentional array which are designed for mathematical and computational efficiency


*   scaler 0
*   vectors (1D tensors): List of numbers
*   matrices (2D tensors): grayscale images
*   4D tensors: batches of RGB images
*   5D tensors: Video Data(combinations of frames and images)





In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.9.0+cu126


In [ ]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print('GPU is not available. Using CPU')


GPU is available
Using GPU: Tesla T4


**CREATING A TENSOR**

In [ ]:
#using empty
a=torch.empty(2,3)

In [ ]:
#check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.9436, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])

In [ ]:
#manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#some other ways to manipulate data

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**TENSOR SHAPES**

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)


tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

**TENSOR DATA TYPES**

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**MATHEMATICAL OPERATIONS**

In [ ]:
x=torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [ ]:
x + 2

tensor([[2.7118, 2.7876, 2.4183],
        [2.9014, 2.9969, 2.7565]])

In [ ]:
x - 2

tensor([[-1.2882, -1.2124, -1.5817],
        [-1.0986, -1.0031, -1.2435]])

In [ ]:
x * 3

tensor([[2.1353, 2.3627, 1.2549],
        [2.7042, 2.9907, 2.2695]])

In [ ]:
x / 3

tensor([[0.2373, 0.2625, 0.1394],
        [0.3005, 0.3323, 0.2522]])

In [ ]:
#int division
(x*100)//3

tensor([[23., 26., 13.],
        [30., 33., 25.]])

In [ ]:
#mod
((x*100)//3)%2


tensor([[1., 0., 1.],
        [0., 1., 1.]])

In [ ]:
#power
x**2

tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

**ELEMENT WISE OPERATIONS**

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [ ]:
#add
a+b

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])

In [ ]:
#multiply
a*b

tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])

In [ ]:
#division
a/b


tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])

In [ ]:
#power
a**b

tensor([[0.5145, 0.3218, 0.2771],
        [0.9096, 0.8672, 0.9839]])

In [ ]:
#mod
a%b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

**REDUCTION OPERATIONS**

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [ ]:
torch.sum(e)

tensor(28.)

In [ ]:
torch.mean(e)

tensor(4.6667)

In [ ]:
torch.mean(e, dim=0)

tensor([8.0000, 2.5000, 3.5000])

In [ ]:
torch.mean(e, dim=1)

tensor([2.3333, 7.0000])

In [ ]:
torch.median(e)

tensor(5.)

In [ ]:
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
torch.prod(e)

tensor(0.)

In [ ]:
torch.std(e)

tensor(3.8297)

In [ ]:
torch.var(e)

tensor(14.6667)

In [ ]:
torch.argmax(e)

tensor(3)

In [ ]:
torch.argmin(e)

tensor(1)

**MATRIX OPERATIONS**

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 9, 4],
        [0, 5, 7]])
tensor([[5, 9],
        [9, 7],
        [5, 9]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[116, 126],
        [ 80,  98]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 0],
        [9, 5],
        [4, 7]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[8., 9., 7.],
        [9., 2., 6.],
        [7., 7., 8.]])

In [ ]:
# determinant
torch.det(h)

tensor(-135.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 0.1926,  0.1704, -0.2963],
        [ 0.2222, -0.1111, -0.1111],
        [-0.3630, -0.0519,  0.4815]])

**COMPARISON OPERATIONS**

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 6, 1],
        [5, 5, 0]])
tensor([[4, 3, 8],
        [8, 3, 3]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

**SPECIAL FUNCTIONS**

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 0., 6.],
        [4., 0., 8.]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094,   -inf, 1.7918],
        [1.3863,   -inf, 2.0794]])

In [ ]:
# exp
torch.exp(k)


tensor([[1.4841e+02, 1.0000e+00, 4.0343e+02],
        [5.4598e+01, 1.0000e+00, 2.9810e+03]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 0.0000, 2.4495],
        [2.0000, 0.0000, 2.8284]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.5000, 0.9975],
        [0.9820, 0.5000, 0.9997]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.7311, 0.5000, 0.1192],
        [0.2689, 0.5000, 0.8808]])

In [ ]:
# relu
torch.relu(k)

tensor([[5., 0., 6.],
        [4., 0., 8.]])

In [ ]:
# relu
torch.relu(k)

tensor([[5., 0., 6.],
        [4., 0., 8.]])

**INPLACE OPERATIONS**

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])
tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])


In [ ]:
m.add_(n)

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [ ]:
m

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [ ]:
n

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
torch.relu(m)

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [ ]:
m.relu_()

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [ ]:
m

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

**COPYING A TENSOR**

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
id(a)

137704464342048

In [ ]:
id(b)

137704464342048

In [ ]:
b = a.clone()

In [ ]:
a[0][0] = 10
a

tensor([[10.0000,  0.7668,  0.1659],
        [ 0.4393,  0.2243,  0.8935]])

In [ ]:
b

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
id(a)

137704464342048

In [ ]:
id(b)

137704464340368

**TENSOR OPERATIONS ON GPU**

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
a= torch.rand(2,3)
a

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
b =a.to(device)

In [ ]:
b + 5

tensor([[5.0497, 5.1780, 5.3011],
        [5.1893, 5.9186, 5.2131]], device='cuda:0')

**NUMPY & PYTORCH**

In [ ]:
import numpy as np

In [ ]:
a=torch.tensor([1,2,3])

In [ ]:
a

tensor([1, 2, 3])

In [ ]:
b=a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])